GET http://localhost:3000/api/wanaka/activity HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTM0NzA1MTIsInVzZXIiOiIzYmQyMzlkNC0wM2QxLTQ3Y2UtYWUyMC1kYjE1YjIzOTgwMTEifQ.cdQ8FX3P3pKYC3U_UHiyAeNCaUEqb99PmUOtJAJxNBI